service:
  name: serverless-ruby

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  timeout: 20

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
